# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c4e1dda8947ea3227cd4c5468e9b17c9b6510b85751fd1ed8186b6fac2c7008880df49ca6724cb64ab6443ff0f0cdf78503e040b5d9f57a2ca1bd994ad2dc87
  ziggeo_secret: <%= ENV["ZIGGEO_TOKEN"] %>

test:
  secret_key_base: 7259651104bce25cb21691fa3cc8dea52097e2b1a596ab1dba576e7ef8034d43a7057f2c14c8a0035c3c363c533ae63340cade62bb74a0f2597a006c28f3f5a4
  ziggeo_secret: <%= ENV["ZIGGEO_TOKEN"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  ziggeo_secret: <%= ENV["ZIGGEO_TOKEN"] %>
